authorName: Anonymous
experimentName: NOKD-Resnet8
trialConcurrency: 1
maxExecDuration: 60h
maxTrialNum: 100

#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python3 train.py --epochs 160 --student resnet14 --cuda True --batch-size 128
  codeDir: .
  gpuNum: 1